
platform :ios, '8.0'

target 'LSTButton_Example' do
  pod 'LSTButton', :path => '../'
  pod 'Masonry'
  pod 'LSTCategory'
   
  target 'LSTButton_Tests' do
    inherit! :search_paths

    
  end
end
